config/routes.rb
Kebapress::Engine.routes.draw do

  resources :dashboard, only: [:index]
  resources :posts, except: [:show, :index]
  resources :categories
  post '/posts/imageUpload', to: 'posts#image_upload'

  get '/', to: 'dashboard#index'
end

app/models/kebapress/category.rb
module Kebapress
  class Category < ActiveRecord::Base
  	has_and_belongs_to_many :posts
  	validates :title, presence: true, uniqueness: true
  end
end

app/models/kebapress/photo.rb
module Kebapress
  class Photo < ActiveRecord::Base
    has_attached_file :image
  end
end

app/models/kebapress/post.rb
module Kebapress
  class Post < ActiveRecord::Base
    # Using scopes for getting published or uncategorized posts at once
    scope :published, -> { where(published: true) }
    scope :uncategorized, -> { includes(:categories).where(kebapress_categories: { id: nil })}

    has_and_belongs_to_many :tags
    has_and_belongs_to_many :categories
    belongs_to :admin, class_name: 'Admin', foreign_key: 'author_id'

    validates :title, presence: true
    validates :body, presence: true
    validates :published, inclusion: { in: [true, false] }
    validates :commentable, inclusion: { in: [true, false] }

    def tag_list=(tags)
      self.tags.clear
      tags.split(',').each do |tag|
        self.tags << Kebapress::Tag.find_or_create_by_title(tag.strip)
      end
    end

    def tag_list
      self.tags.collect do |tag|
        tag.title
      end.join(', ')
    end
  end
end

app/models/kebapress/tag.rb
module Kebapress
  class Tag < ActiveRecord::Base
  	has_and_belongs_to_many :posts
  	validates :title, presence: true, uniqueness: true
  end
end

app/controllers/kebapress/application_controller.rb
module Kebapress
  class ApplicationController < ActionController::Base
    before_filter :authenticate_admin!
    # Using Cybele app's layout for default
    layout Rails.configuration.kebapress.admin_layout
  end
end

app/controllers/kebapress/categories_controller.rb
require_dependency 'kebapress/application_controller'

module Kebapress
  class CategoriesController < ApplicationController
    def show
      @posts = Kebapress::Category.find(params[:id]).posts
    end

    def new
      @category = Kebapress::Category.new
    end

    def create
      @category = Kebapress::Category.create(category_params)

      if @category.save
        redirect_to '/hq/blog/dashboard'
      else
        render 'new'
      end
    end

    def edit
      @category = Kebapress::Category.find(params[:id])
    end

    def update
      @category = Kebapress::Category.find(params[:id])
      @category.update(category_params)
      redirect_to '/hq/blog/dashboard'
    end

    def destroy
      @category = Kebapress::Category.find(params[:id])
      @category.destroy

      redirect_to '/hq/blog/dashboard'
    end

    private
      def category_params
        params.require(:category).permit(:title)
      end
  end
end

app/controllers/kebapress/dashboard_controller.rb
require_dependency 'kebapress/application_controller'

module Kebapress
  class DashboardController < ApplicationController
    def index
      @posts = Kebapress::Post.order('created_at DESC')
      @categories = Kebapress::Category.order('created_at DESC')
    end
  end
end

app/controllers/kebapress/posts_controller.rb
require_dependency 'kebapress/application_controller'

module Kebapress
  class PostsController < ApplicationController
    skip_before_filter :authenticate_admin!, only: [:show, :index]
    def new
      @post = Kebapress::Post.new
      @categories = Kebapress::Category.all
    end

    def index
      @posts = Kebapress::Post.published.order('published_at DESC')
      render layout: Rails.configuration.kebapress.front_layout, template: 'kebapress/blog/index'
    end

    def show
      @post = Kebapress::Post.find(params[:id])
      render layout: Rails.configuration.kebapress.front_layout, template: 'kebapress/blog/show'
    end

    def create
      @post = Kebapress::Post.new(post_params)

      # params[:boolean_variable] returns 'true' or 'nil'
      # So we have to assign false value by using unless true
      @post.commentable = false unless @post.commentable
      @post.published = false unless @post.published
      @post.published_at = Time.now if @post.published

      # Relating post with Cybele app's current admin
      @post.admin = current_admin

      if @post.save
        redirect_to '/hq/blog/dashboard'
      else
        # On an error, a new page will be rendered
        # but it won't be rendered by new method.
        # So we need to get all Categories again.
        @categories = Kebapress::Category.all
        render 'new'
      end
    end

    def edit
      @post = Kebapress::Post.find(params[:id])
      @categories = Kebapress::Category.all
    end

    def update
      params[:post][:category_ids] ||= []
      @post = Kebapress::Post.find(params[:id])

      @post.commentable = false unless params[:commentable]
      @post.published = params[:post][:published] ? true : false
      @post.published_at ||= Time.now if @post.published

      @post.update(post_params)

      redirect_to '/hq/blog/dashboard'
    end

    def destroy
      @post = Kebapress::Post.find(params[:id])
      @post.destroy

      redirect_to '/hq/blog/dashboard'
    end

    def image_upload
      @photo = Photo.create(image: params[:file])
      # Rendering image's url as text for
      # Medium Editor Insert Plugin
      render text: @photo.image.url
    end

    private
      def post_params
        params.require(:post).permit(:title, :body, :published, :commentable, :tag_list, { category_ids: [] })
      end
  end
end

app/helpers/kebapress/application_helper.rb
module Kebapress
  module ApplicationHelper
  end
end

app/helpers/kebapress/categories_helper.rb
module Kebapress
  module CategoriesHelper
  end
end

app/helpers/kebapress/dashboard_helper.rb
module Kebapress
  module DashboardHelper
  end
end

app/helpers/kebapress/posts_helper.rb
module Kebapress
  module PostsHelper
  end
end

app/views/kebapress/categories/_form.html.haml
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = yield :form_title

  .panel-body
    =simple_form_for @category do |f|
      = f.error_notification

      .form-inputs
        = f.input :title, label: I18n.t('kebapress.title')

      .form-actions
        = f.button :submit, yield(:button), class: 'btn btn-default'
        = link_to I18n.t('kebapress.cancel_button'), '/hq/blog', class: 'btn'

app/views/kebapress/categories/edit.html.haml
- content_for :form_title do
  #{I18n.t('kebapress.edit_category')}

- content_for :button do
  #{I18n.t('kebapress.update_category_button')}

= render 'form'

app/views/kebapress/categories/new.html.haml
- content_for :form_title do
  #{I18n.t('kebapress.new_category')}

- content_for :button do
  #{I18n.t('kebapress.create_category_button')}

= render 'form'

app/views/kebapress/categories/show.html.haml
-@posts.each do |post|
  %p= link_to post.title, post_path(post)

app/views/kebapress/dashboard/index.html.haml
= link_to I18n.t('kebapress.new_post'), new_post_path, method: :get, class: 'btn btn-default btn-success pull-right'
%br
%br
.panel.panel-default.grid
  .panel-heading
    %i.icon-table.icon-large
    #{I18n.t('kebapress.posts')}

  %table.table
    %thead
      %tr
        %th #
        %th #{I18n.t('kebapress.title')}
        %th.actions
          #{I18n.t('kebapress.action')}

    %tbody.success
      - @posts.each do |post|
        %tr
          %td
            = (@posts.index post) + 1
          %td
            = post.title
          %td.action
            %a.btn.btn-success{href: main_app.pages_path(post), data: {toggle: 'tooltip'}, title: I18n.t('kebapress.show')}
              %i.icon-zoom-in
            %a.btn.btn-info{href: edit_post_path(post)}
              %i.icon-edit
            = link_to post_path(post), method: :delete, data: { confirm: I18n.t('kebapress.ru_sure') }, class: 'btn btn-danger' do
              %i.icon-trash

= link_to I18n.t('kebapress.new_category'), new_category_path, method: :get, class: 'btn btn-default btn-success pull-right'
%br
%br
.panel.panel-default.grid
  .panel-heading
    %i.icon-table.icon-large
    #{I18n.t('kebapress.categories')}

  %table.table
    %thead
      %tr
        %th #
        %th #{I18n.t('kebapress.title')}
        %th.actions
          #{I18n.t('kebapress.action')}

    %tbody.success
      - @categories.each do |category|
        %tr
          %td
            = (@categories.index category) + 1
          %td
            = category.title
          %td.action
            %a.btn.btn-info{href: edit_category_path(category)}
              %i.icon-edit
            = link_to category_path(category), method: :delete, data: { confirm: I18n.t('kebapress.ru_sure') }, class: 'btn btn-danger' do
              %i.icon-trash

app/views/kebapress/posts/_form.html.haml
- content_for :head do
  =stylesheet_link_tag 'kebapress/application'

- content_for :foot do
  = javascript_include_tag 'kebapress/posts'


.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = yield :form_title

  .panel-body
    = simple_form_for @post do |f|
      = f.error_notification

      .form-inputs
        = f.input :title, label: I18n.t('kebapress.title')
        = f.label :body, label: I18n.t('kebapress.body')
        = f.input :body, input_html: { id: 'post_body' }, as: :hidden
        .editable{data: {field: {id: 'body'}, placeholder: ' '}}

        %br
        = f.input :published, as: :boolean, label: false, inline_label: I18n.t('kebapress.published')
        = f.input :commentable, as: :boolean, label: false, inline_label: I18n.t('kebapress.commentable')

        = f.label I18n.t('kebapress.categories')
        - @categories.each do |category|
          .categories.checkbox
            =check_box_tag 'post[category_ids][]', category.id, @post.categories.include?(category)
            =category.title

      .form-actions
        = f.button :submit, yield(:button), class: 'btn btn-default'
        = link_to I18n.t('kebapress.cancel_button'), '/hq/blog', class: 'btn'

app/views/kebapress/posts/edit.html.haml
- content_for :form_title do
  #{I18n.t('kebapress.edit_post')}

- content_for :button do
  #{I18n.t('kebapress.update_post_button')}

= render 'form'

app/views/kebapress/posts/index.html.haml
.index-page.container
  .posts-container
    - @posts.each do |post|
      .post-container
        .post-title
          %h2= link_to post.title, post_path(post)
        .post-body
          %p= post.body.html_safe
        .bottom
          .categories
            %h5= 'Categories:'
            - post.categories.each do |category|
              %span.label.label-info= link_to category.title + ', ', '#'

          .tags
            %h5= 'Tags:'
            - post.tags.each do |tag|
              %span.label.label-info= link_to tag.title + ', ', '#'

app/views/kebapress/posts/new.html.haml
- content_for :form_title do
  #{I18n.t('kebapress.new_post')}

- content_for :button do
  #{I18n.t('kebapress.create_post_button')}

= render 'form'

app/views/kebapress/posts/show.html.haml
.post.container
  .title.page-header
    %h1= @post.title
  .info
    - if @post.published
      %p= "Posted at " + @post.published_at.strftime("%m/%d/%Y")
  .body
    %p.lead= @post.body.html_safe
  .bottom
    .categories
      %h5= "Categories:"
      - @post.categories.each do |category|
        %span.label.label-info= link_to category.title + ", ", "#"

    .tags
      %h5= "Tags:"
      - @post.tags.each do |tag|
        %span.label.label-info= link_to tag.title + ", ", "#"

app/views/layouts/kebapress/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kebapress</title>
  <%= stylesheet_link_tag    "kebapress/application", media: "all" %>
  <%= javascript_include_tag "kebapress/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>